### PR TITLE
adds custom scrollbars + adds container for About page

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by euotiniel** [comment]
@diomed, yes, do you readed my mind!

**Comment by mickasmt** [comment]
I updated the container for the about page (with mainClass).
The scrollbar was included as a comment to offer users a choice.
Thanks for the pull request.

**Comment by diomed** [comment]
> I updated the container for the about page (with mainClass). The scrollbar was included as a comment to offer users a choice. Thanks for the pull request.

thank you. you have a great approach.

**Comment by diomed** [comment]
would you mind if I made a PR for FAQ page?

**Comment by mickasmt** [comment]
@diomed  you can! It doesn't bother me.

**Pull request closed without merging**
